### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by stancatalin** [foliovision/fv-top-level-cats#11]
Hi @foliovision  

I am using your product and it's working great!!

I noticed that you are missing the license.
Can you, please make an update with the license?
Would be an option for you to use https://opensource.org/licenses/MIT ? I can make an PR with this

Thank you

**Comment by foliovision** [comment]
Hello Stan,

the license information was added to readme.txt as well as the license.txt file.

I also tested the plugin on WordPress 5.3 and found no issues.

Thanks,
Martin
