### ISSUE TITLE
Version 1.8 disappear?

### ISSUE THREAD

**Issue by odie2** [foliovision/fv-top-level-cats#5]
Hi,

I just wasted 2 hours trying figure why pages on categories won't work for me.
Forgot that I did that very important fix for me with `pagination_base` and had it only on one production server.

As I remember version 1.8 was available and then disappear?
What's going on? This is third plugin that I discovered in 15 hours that had newest version with extremely important changes commited by me, but then this version just disappear... So I have 3 plugins behing WP repository and have to upload plugins by ftp to many websites...

Hope to fast fix to release version 1.8 (again?).
Greetings

**Comment by foliovision** [comment]
Hello odie2,

is the version here in Github the one you need? I'm not sure why it's not on WordPress.org, perhaps I forgot to release it.

Sorry about that, version 1.8 is out now.

Thanks,
Martin

**Comment by odie2** [comment]
Many thanks :)
